#!/usr/bin/python3
# library to get arguments
import sys


# fn unpack number factorial
def fc():
    """
    function fc to search file to convert number and format n=p*q
    """
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for revnum in f:
                revnum = int(revnum)
                if revnum % 2 == 0:
                    print("{}={}*{}".format(revnum, revnum // 2, 2))
                    continue
                i = 3
                while i < revnum // 2:
                    if revnum % i == 0:
                        print("{}={}*{}".format(revnum, revnum // i, i))
                        break
                    i = i + 2
                if i == (revnum // 2) + 1:
                    print("{}={}*{}".format(revnum, revnum, 1))
    except (IndexError):
        pass


# autostart
fc()
