#!/usr/bin/python3
import sys


def fc():
    """
    function fc to search file to convert number and format n=p*q
    """
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for revnumber in f:
                revnumber = int(revnumber.strip())
                if revnumber % 2 == 0:
                    print("{}={}*{}".format(revnumber, 2, revnumber // 2))
                    continue
                i = 3
                while i <= int(revnumber**0.5):
                    if revnumber % i == 0:
                        print("{}={}*{}".format(revnumber, i, revnumber // i))
                        break
                    i += 2
                else:
                    print("{}={}*{}".format(revnumber, revnumber, 1))
    except IndexError:
        print("Please provide a filename as an argument.")
    except FileNotFoundError:
        print(f"File '{revfile}' not found.")
    except ValueError:
        print("Invalid number in the file.")


if __name__ == "__main__":
    fc()
